name: Java CI

on: push

jobs:

  deploy-snapshot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Info
        run: mvn -version
      - name: Deploy Info
        run: cat ~/.m2/settings.xml
      - name: Deploy
        run: mvn -e --no-transfer-progress deploy -Dgpg.skip=true -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
