name: Java CI

on: push

jobs:

  deploy-snapshot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Info
        run: mvn -version
      - name: Deploy
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/rashtao/test-gh-packages -Dtoken=${{secrets.GITHUB_TOKEN}} -Dgpg.skip=true -DskipTests=true
